trigger:
  branches:
    include:
      - '*'
    exclude:
      - develop

jobs:
- template: template--core-nuget-package.yml
  parameters:
    name: 'WorkFlowAbstractions'
    project: 'WorkFlow.Abstractions/WorkFlow.Abstractions.csproj'
    packageVersionNumberSuffix: '-$(Build.SourceBranchName)'
    buildConfiguration: 'Debug'
    